### PR TITLE
Fix some typos.

### PR DESCRIPTION
**Pull request by rb214678**
Fix some typos in code and Doxygen comments.

### CODE REVIEW

**Review by tpadioleau — DISMISSED** [review]
Good catch, did you use any tool to get them ?

**Review by yasahi-hpc — DISMISSED** [review]
Nice fix, thank

**Comment by yasahi-hpc** [comment]
> There is also an other typo in unit_test/Test_Transform.cpp "neeed" that I did not fix because I don't know if it should be "need" or "needed". If you tell me I can rework my PR.

Regrading "neeed", they are supposed to be "needed". Could you please also fix them

**Comment by rb214678** [comment]
> Good catch, did you use any tool to get them ?

While reviewing a pull request, I noticed a first typo and then I decided to check if there were other typos. For this I used the spelling checker inside Vim.

**Comment by yasahi-hpc** [comment]
> > > There is also an other typo in unit_test/Test_Transform.cpp "neeed" that I did not fix because I don't know if it should be "need" or "needed". If you tell me I can rework my PR.
> > 
> > 
> > Regrading "neeed", they are supposed to be "needed". Could you please also fix them
> 
> I have done the update.

Thanks!

**Comment by yasahi-hpc** [comment]
> > Good catch, did you use any tool to get them ?
> 
> While reviewing a pull request, I noticed a first typo and then I decided to check if there were other typos. For this I used the spelling checker inside Vim.

That is interesting. I will look for a tool to make it automatically in CI

**Review by yasahi-hpc — APPROVED** [review]

**Comment by rb214678** [comment]
Just a small question : some CI tests failed (also yesterday for my first version of the PR) is it normal or expected ?

**Comment by yasahi-hpc** [comment]
> Just a small question : some CI tests failed (also yesterday for my first version of the PR) is it normal or expected ?

Hmm, it seems the expected behavior, because you are not whitelisted to run CI on ruche.
https://github.com/kokkos/kokkos-fft/actions/runs/12135732423/job/33836388569#step:2:6

**Comment by rb214678** [comment]
> > Just a small question : some CI tests failed (also yesterday for my first version of the PR) is it normal or expected ?
> 
> Hmm, it seems the expected behavior, because you are not whitelisted to run CI on ruche. https://github.com/kokkos/kokkos-fft/actions/runs/12135732423/job/33836388569#step:2:6

Ok, thanks for the answer.

**Pull request merged**
