### PR TITLE
rename KokkosFFT_layouts.hpp to KokkosFFT_Extents.hpp

### PR DESCRIPTION
**Pull request by yasahi-hpc**
In this PR, `KokkosFFT_layouts.hpp` is renamed as `KokkosFFT_Extents.hpp`.
All the header files are planned to be renamed in this manner (`KokkosFFT_` + name in Uppercase).

### CODE REVIEW

**Review by tpadioleau — APPROVED** [review]
LGTM

**Comment by tpadioleau** [comment]
> All the header files are planned to be renamed in this manner (`KokkosFFT_` + name in Uppercase).

Can you make it a script to ease reviewing ? Like
```
for each KokkosFFT_file in KokkosFFT:
   rename it KokkosFFT_File
   replace all include occurences
```

**Comment by yasahi-hpc** [comment]
@tpadioleau Thank you for your review

> > All the header files are planned to be renamed in this manner (`KokkosFFT_` + name in Uppercase).
> 
> Can you make it a script to ease reviewing ? Like
> 
> ```
> for each KokkosFFT_file in KokkosFFT:
>    rename it KokkosFFT_File
>    replace all include occurences
> ```

OK. For the next change, I will include a script to check that.
This PR is a little bit different, since it also changes the file name.

**Comment by yasahi-hpc** [comment]
I will merge this

**Pull request merged**
