### PR TITLE
Use if constexpr for compile time if conditional

### PR DESCRIPTION
**Pull request by yasahi-hpc**
In this PR, we use `if constexpr` for compile time if conditional.

### CODE REVIEW

**Review by tpadioleau — APPROVED** [review]
Ok for me, I compiled withtout `[[maybe_unused]]` and did not get any warning :D compilers...

**Comment by yasahi-hpc** [comment]
> Ok for me, I compiled withtout `[[maybe_unused]]` and did not get any warning :D compilers...

It is a bit surprising. Should we remove that then?

**Comment by tpadioleau** [comment]
> Should we remove that then?

No I think it is legitimate to keep it, there is a compile-time path where the variable is not used.

**Comment by yasahi-hpc** [comment]
Thanks for comments. I will merge this.

**Pull request merged**
