### PR TITLE
Update CI script for Ruche

### PR DESCRIPTION
**Pull request by pzehner**
This PR aims to update CI scripts following the use of containers on Ruche.

### CODE REVIEW

**Comment by yasahi-hpc** [comment]
Thank you for the PR.
LGTM.

I have some questions about `run-cpu` and `run-gpu` scripts.
If I understand correctly, these scripts are placed at the same directory as the runner and are not exposed to public. 
Could you please share these scripts somewhere for the better understanding of future changes?

**Review by yasahi-hpc — APPROVED** [review]

**Comment by pzehner** [comment]
Everything seems to work. As a good side effect, I could update `upload`/`download-artifact` to v4.

Your comment raises a really good point about how to document these scripts internally (they have few options, but they should not be let undocumnented).

**Comment by yasahi-hpc** [comment]
Sure. I will merge this

**Comment by pzehner** [comment]
Wait, it wasn't ready for merging...

**Comment by yasahi-hpc** [comment]
Oh, sorry

**Pull request merged**
