### PR TITLE
Rely on the user allocation in `ihfft`

### PR DESCRIPTION
**Pull request by tpadioleau**
Are we sure we want to discard the user allocation ?

### CODE REVIEW

**Comment by tpadioleau** [comment]
linked to #158

**Review by yasahi-hpc — APPROVED** [review]
LGTM.
May be less performant than the original implementation?

**Comment by tpadioleau** [comment]
> LGTM. May be less performant than the original implementation?

For now yes, I think the `conjugate` operation could be executed in-place ? We could get rid of the `out_conj` array.

**Comment by yasahi-hpc** [comment]
> > LGTM. May be less performant than the original implementation?
> 
> For now yes, I think the `conjugate` operation could be executed in-place ? We could get rid of the `out_conj` array.

For this use case, we can make it in-place. For `hfft` with real input (not implemented yet), I need an out-place version of `conjugate` since it involves the data type conversion from `real` to `complex`. For this, I need to implement a helper to define a complex typed View from real typed View, like

```C++
View<double ***> -> View<Kokkos::complex<double> ***>
```

**Comment by tpadioleau** [comment]
I see I agree

**Pull request merged**
