### PR TITLE
Rename complex number to avoid confusion with the imaginary unit

### PR DESCRIPTION
**Pull request by tpadioleau**
I suspect a typo about the value of `I` which I guess represent the imaginary unit ?

### CODE REVIEW

**Comment by yasahi-hpc** [comment]
Actually, this value is nothing to do with the imaginary unit. So it should be renamed. 
This value `Kokkos::complex<double>(1.0, 1.0)` is intended to get a random complex random number `x` which satisfies`Kokkos::complex<double>(0.0, 0.0) < x < Kokkos::complex<double>(1.0, 1.0)`.

**Comment by tpadioleau** [comment]
> Actually, this value is nothing to do with the imaginary unit. So it should be renamed.

I see, what do you think of `z` or `c`, I used to see a lot this naming in math lessons ?

> This value `Kokkos::complex<double>(1.0, 1.0)` is intended to get a random complex random number `x` which satisfies`Kokkos::complex<double>(0.0, 0.0) < x < Kokkos::complex<double>(1.0, 1.0)`.

You mean a random number on the segment $\\{t (1 + i), t \in [0, 1]\\}$ ? Actually I didn't find any information about `fill_random`.

**Comment by yasahi-hpc** [comment]
> > Actually, this value is nothing to do with the imaginary unit. So it should be renamed.
> 
> I see, what do you think of `z` or `c`, I used to see a lot this naming in math lessons ?

I personally prefer `z`, but nothing is wrong with `c`.
 
> > This value `Kokkos::complex<double>(1.0, 1.0)` is intended to get a random complex random number `x` which satisfies`Kokkos::complex<double>(0.0, 0.0) < x < Kokkos::complex<double>(1.0, 1.0)`.
> 
> You mean a random number on the segment { t ( 1 + i ) , t ∈ [ 0 , 1 ] } ? Actually I didn't find any information about `fill_random`.

Exactly. According to the docstring in the [source code](https://github.com/kokkos/kokkos/blob/4e88587265240078b2d6d94261d118e7a4a15cea/algorithms/src/Kokkos_Random.hpp#L200-L202), it would return the random numbers of the type in the range `[0,range)`

**Comment by tpadioleau** [comment]
> I personally prefer `z`, but nothing is wrong with `c`.

I will rename accordingly.

> Exactly. According to the docstring in the [source code](https://github.com/kokkos/kokkos/blob/4e88587265240078b2d6d94261d118e7a4a15cea/algorithms/src/Kokkos_Random.hpp#L200-L202), it would return the random numbers of the type in the range `[0,range)`

I find the notation `[0, range)` a bit ambiguous for complex numbers as there is no natural order for complex numbers.

**Comment by tpadioleau** [comment]
done 4693fada061a6101d6ec08e4c34d81e58f190e18

**Comment by yasahi-hpc** [comment]
> > I personally prefer `z`, but nothing is wrong with `c`.
> 
> I will rename accordingly.

Thanks!

> > Exactly. According to the docstring in the [source code](https://github.com/kokkos/kokkos/blob/4e88587265240078b2d6d94261d118e7a4a15cea/algorithms/src/Kokkos_Random.hpp#L200-L202), it would return the random numbers of the type in the range `[0,range)`
> 
> I find the notation `[0, range)` a bit ambiguous for complex numbers as there is no natural order for complex numbers.

That is true. Actually, I could not find the detailed documentations for this function.

**Review by yasahi-hpc — APPROVED** [review]
LGTM. 
I will merge this

**Comment by tpadioleau** [comment]
> Exactly. According to the docstring in the [source code](https://github.com/kokkos/kokkos/blob/4e88587265240078b2d6d94261d118e7a4a15cea/algorithms/src/Kokkos_Random.hpp#L200-L202), it would return the random numbers of the type in the range `[0,range)`

Actually it seems to generate random numbers for each component, real and imaginary, see https://github.com/kokkos/kokkos/blob/4e88587265240078b2d6d94261d118e7a4a15cea/algorithms/src/Kokkos_Random.hpp#L544-L551

**Pull request merged**
