### PR TITLE
Update docs license

### LINKED ISSUE #84: nvcc version should be 11.0

### LINKED ISSUE #86: LICENCSE: Apache 2 LLVM exception

### PR DESCRIPTION
**Pull request by yasahi-hpc**
Resolves #86
Resolves #84 

In this PR,
1. Update the License to The Apache 2.0 License with LLVM Exception or the MIT License.
2. Update the paths in README.md and docs
3. Embed new licenses

### CODE REVIEW

**Comment by jbigot** [comment]
We should offer both MIT & Apache-2 at the user's discretion

**Comment by jbigot** [comment]
Also, we should follow [reuse](https://reuse.software) spec

**Comment by yasahi-hpc** [comment]
@jbigot Modified accordingly

**Comment by jbigot** [comment]
Fixed, should be good now

**Comment by yasahi-hpc** [comment]
@jbigot 
Thanks!
I have two questions. 
1. Under LICENSES folder, we have BSD and CC0 licenses. Do we need them?
2. It seems that <License>.txt files are just templates. We do not need to embed our information?

**Comment by jbigot** [comment]
We need BSD & CC0 because we have a few files that use them, namely FindFFTW for BSD & the reuse check for CC0, if we remove them the check will fail.

I don't believe we should embed any info in the licence files. The info is available from other places.

**Comment by yasahi-hpc** [comment]
Sure. Thank you for your explanation.
I will merge this and work on other issues

**Pull request merged**
